apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-conf-pvc
  namespace: jellyfin
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-nvme
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-raid5
  resources:
    requests:
      storage: 3.9T