---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system-traefik
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-25.0.3+up25.0.0.tgz
  set:
    global.systemDefaultRegistry: ""
  targetNamespace: kube-system-traefik
  # Reference: https://github.com/traefik/traefik-helm-chart/blob/e03b1287af6a9dfafb2d4203068f40c801e0f9b4/traefik/VALUES.md
  valuesContent: |-
    deployment:
      podAnnotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: false
        allowExternalNameServices: true
        # -- Allows to return 503 when there is no endpoints available
        allowEmptyServices: true
      kubernetesIngress:
        enabled: false
    hostNetwork: false
    priorityClassName: "system-cluster-critical"
    nodeSelector:
      svccontroller.k3s.cattle.io/enablelb: "true"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "2.10.7"
      pullPolicy: IfNotPresent
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "app"
      operator: "Equal"
      values:
        - compute
      effect: "NoSchedule"
    service:
      enabled: true
      single: false
      type: LoadBalancer
      ipFamilyPolicy: "SingleStack"
      spec: {}
      ipFamilies:
        - IPv4
      externalIPs:
        - 10.50.0.2
      ## -- An additional and optional internal Service.
      ## Same parameters as external Service
      internal:
        type: ClusterIP
        enabled: true
        single: false
        ipFamilyPolicy: "SingleStack"
        ipFamilies:
          - IPv4
    logs:
      general:
        # format: json
        # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: INFO
      access:
        enabled: true
