---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: jellyfin
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-appdata
  resources:
    requests:
      storage: 3.9T
