---
- name: Base System Setup
  hosts: rpi5-0
  remote_user: root
  vars:
    src_etc_containers: ../butane/base/coreos/etc/containers
    dest_etc_containers_d: /etc/containers/containers.conf.d
  tasks:
    - name: Update all packages (pacman -Syu)
      community.general.pacman:
        update_cache: true
        upgrade: true
      tags:
        - packages.update

    - name: Set hostname
      ansible.builtin.copy:
        content: |
          rpi5-0.expresso.lan
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0400'

    - name: Install v4l2loopback-dkms
      community.general.pacman:
        name: extra/v4l2loopback-dkms
        state: present
      tags:
        - packages.install
        - packages.install.v4l2

    - name: Install v4l2loopback-utils
      community.general.pacman:
        name: extra/v4l2loopback-utils
        state: present
      tags:
        - packages.install
        - packages.install.v4l2

    - name: Install v4l2loopback-utils
      community.general.pacman:
        name: extra/v4l-utils
        state: present
      tags:
        - packages.install
        - packages.install.v4l2

    - name: Install zram-generator
      community.general.pacman:
        name: extra/zram-generator
        state: present
      tags:
        - packages.install
        - zram-generator

    - name: Install alarm/raspberrypi-utils
      community.general.pacman:
        name: alarm/raspberrypi-utils
        state: present
      tags:
        - packages.install

    - name: Install tuned
      community.general.pacman:
        name: extra/tuned
        state: present
      tags:
        - packages.install
        - tuned

    - name: Install package podman
      community.general.pacman:
        name: podman
        state: present
      tags:
        - packages.install

    - name: Install package podman-docker
      community.general.pacman:
        name: podman-docker
        state: present
      tags:
        - packages.install

    - name: Install package bash-completion
      community.general.pacman:
        name: bash-completion
        state: present
      tags:
        - packages.install
        - packages.install.optional

    - name: Install package vim
      community.general.pacman:
        name: vim
        state: present
      tags:
        - packages.install
        - packages.install.optional

    - name: Install package htop
      community.general.pacman:
        name: htop
        state: present
      tags:
        - packages.install
        - packages.install.optional

    - name: Install package lsusb
      community.general.pacman:
        name: extra/cyme
        state: present
      tags:
        - packages.install
        - packages.install.optional

    # Used for exporting metrics to Prometheus
    - name: Install package extra/pcp-pmda-podman
      community.general.pacman:
        name: extra/pcp-pmda-podman
        state: present
      tags:
        - packages.install

    - name: Install tree (required for alsa-info.sh)
      community.general.pacman:
        name: tree
        state: present
      tags:
        - packages.install

    - name: Install alsa-utils
      community.general.pacman:
        name: extra/alsa-utils
        state: present
      tags:
        - packages.install

    - name: Enable and Start tuned service
      ansible.builtin.systemd_service:
        name: tuned
        state: started
        enabled: true
      tags:
        - packages.install

    - name: Configure zram-generator
      ansible.builtin.copy:
        content: |
          [zram0]
          zram-size = min(ram / 2, 4096)
          compression-algorithm = zstd
        dest: /etc/systemd/zram-generator.conf
        owner: root
        group: root
        mode: '0644'
      tags:
        - zram-generator
        - zram-generator.configure

    - name: Enable and Start systemd-zram-setup@zram0.service
      ansible.builtin.systemd_service:
        name: systemd-zram-setup@zram0.service
        state: started
        daemon_reload: true
      tags:
        - zram-generator
        - zram-generator.start

    - name: Set tuned profile throughput-performance
      ansible.builtin.command:
        argv:
          - tuned-adm
          - profile
          - throughput-performance
      register: tuned_adm_output
      changed_when: tuned_adm_output.rc == 0
      tags:
        - tuned

    # Used to add route drop-in configs during agent setup
    - name: Create end0.network.d drop-in directory
      ansible.builtin.file:
        path: /etc/systemd/network/end0.network.d
        state: directory
        mode: '0755'
      tags:
        - systemd-networkd
        - systemd-networkd.drop-ins

    - name: Copy end0 ethernet configuration
      ansible.builtin.copy:
        content: |
          [Match]
          Name=end0

          [Network]
          Address={{ ansible_host }}/24
          Gateway={{ NETWORK.GATEWAY_IP }}
          DNS={{ NETWORK.DNS_IP }}
          IPv4Forwarding=yes
          IPv4AcceptLocal=yes
          DHCP=no
          DNSSEC=no
        dest: /etc/systemd/network/end0.network
        owner: root
        group: root
        mode: '0644'
      tags:
        - systemd-networkd

    - name: Remove default en.network config file
      ansible.builtin.file:
        path: /etc/systemd/network/en.network
        state: absent
      tags:
        - systemd-networkd

    - name: Create directory /etc/systemd/networkd.conf.d for drop-ins
      ansible.builtin.file:
        path: /etc/systemd/networkd.conf.d
        state: directory
        mode: '0750'
      tags:
        - systemd-networkd

    - name: Create 90-speedmeter.conf systemd-networkd drop-in
      ansible.builtin.copy:
        dest: /etc/systemd/networkd.conf.d/90-speedmeter.conf
        content: |
          [Network]
          SpeedMeter=true
          SpeedMeterIntervalSec=10sec
        mode: '0644'
        # validate: systemd-analyze cat-config %s
      tags:
        - systemd-networkd

    - name: Create 90-ip-forward.conf systemd-networkd drop-in
      ansible.builtin.copy:
        dest: /etc/systemd/networkd.conf.d/90-ipv4-forward.conf
        content: |
          [Network]
          IPv4Forwarding=true
          IPv6Forwarding=false
        mode: '0644'
        # validate: systemd-analyze cat-config %s
      tags:
        - systemd-networkd

    - name: Reload systemd-networkd configuration
      ansible.builtin.command:
        argv:
          - systemctl
          - reload
          - systemd-networkd
      register: systemctl_reload
      changed_when: systemctl_reload.rc == 0
      tags:
        - systemd-networkd

    - name: Enable podman.socket
      ansible.builtin.systemd_service:
        name: podman.socket
        enabled: true
      tags:
        - services

    - name: Delete {{ dest_etc_containers_d }}
      ansible.builtin.file:
        path: "{{ dest_etc_containers_d }}"
        state: absent
      tags:
        - containers.conf

    - name: Create {{ dest_etc_containers_d }}
      ansible.builtin.file:
        path: "{{ dest_etc_containers_d }}"
        state: directory
        mode: '0755'
      tags:
        - containers.conf

    - name: Copy containers.conf.d/containers-containers.conf
      ansible.builtin.copy:
        dest: "{{ dest_etc_containers_d }}/containers-containers.conf"
        src: "{{ src_etc_containers }}/containers.conf.d/containers-containers.conf"
        mode: '0644'
        owner: root
        group: root
      tags:
        - containers.conf
        - containers.conf.containers

    - name: Copy containers.conf.d/containers-engine.conf
      ansible.builtin.copy:
        dest: "{{ dest_etc_containers_d }}/containers-engine.conf"
        content: |
          [engine]
          # https://github.com/containers/common/blob/main/docs/containers.conf.5.md#engine-table

          # Creates a more verbose container-create event which includes a JSON payload with detailed information about the container. Set to false by default.
          events_container_create_inspect_data = true

          # Selects which logging mechanism to use for container engine events.
          # Valid values are `journald`, `file` and `none`.
          #
          events_logger = "journald"

          # Default OCI runtime
          #
          runtime = "runc"

          # List of the OCI runtimes that support --format=json. When json is supported
          # engine will use it for reporting nicer errors.
          #
          runtime_supports_json = ["crun", "runc", "kata", "runsc", "youki", "krun"]

          # List of the OCI runtimes that supports running containers with KVM Separation.
          #
          runtime_supports_kvm = ["kata", "krun"]

          # List of the OCI runtimes that supports running containers without cgroups.
          #
          runtime_supports_nocgroups = ["crun", "krun"]
        mode: '0644'
        owner: root
        group: root
      tags:
        - containers.conf
        - containers.conf.engine

    - name: Copy containers.conf.d/containers-firewall.conf
      ansible.builtin.copy:
        dest: "{{ dest_etc_containers_d }}/containers-firewall.conf"
        src: "{{ src_etc_containers }}/containers.conf.d/containers-firewall.conf"
        mode: '0644'
        owner: root
        group: root
      tags:
        - containers.conf
        - containers.conf.firewall

    - name: Copy /etc/containers/storage.conf
      ansible.builtin.copy:
        dest: /etc/containers/storage.conf
        src: "{{ src_etc_containers }}/storage.conf"
        mode: '0644'
        owner: root
        group: root
      tags:
        - containers.conf
        - containers.conf.storage
