---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-mw
  namespace: jellyfin
spec:
  headers:
    sslRedirect: true
    customResponseHeaders:
      X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      X-XSS-PROTECTION: "1"
    customFrameOptionsValue: 'allow-from https://expresso.lan'
    stsSeconds: 315360000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    frameDeny: true
    contentTypeNosniff: true
    # TODO setup regex to redirect http to https
