apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      name: jellyfin
      namespace: jellyfin
      labels:
        app: jellyfin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - compute
      containers:
      - name: jellyfin
        livenessProbe:
          tcpSocket:
            port: http-web-svc
          initialDelaySeconds: 120
        env:
        # See for more information: https://jellyfin.org/docs/general/administration/configuration/
        - name: JELLYFIN_PublishedServerUrl
          value: https://jellyfin.rick.expresso.lan
        # Places data dir under /config
        # /config/data
        - name: JELLYFIN_DATA_DIR
          value: /data
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: webpassword
              key: password
              optional: false
        image: docker.io/linuxserver/jellyfin:latest
        ports:
        - containerPort: 8096
          name: http-web-svc
          protocol: TCP
        securityContext:
          privileged: true
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        volumeMounts:
        - name: media
          mountPath: /media
        - name: data
          mountPath: /config/data
          subPath: data
        - name: cache
          mountPath: /config/cache
          subPath: cache
        - name: dev-dri
          mountPath: /dev/dri/renderD128
        - name: logs
          mountPath: /config/log
          subPath: log
        - name: transcodes
          mountPath: /config/data/transcodes
          subPath: transcodes
        resources:
          requests:
            memory: "15G"
            cpu: "500m"
          limits:
            memory: "15G"
            cpu: "2500m"
      enableServiceLinks: false
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
      - name: data
        persistentVolumeClaim:
          claimName: jellyfin-data-pvc
      - name: dev-dri
        hostPath:
          path: /dev/dri/renderD128
          type: CharDevice
      - name: card1
        hostPath:
          path: /dev/dri/card1
          type: CharDevice
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      - name: logs
        emptyDir:
          medium: Memory
          sizeLimit: 500Mi
      - name: transcodes
        emptyDir:
          medium: Memory
          sizeLimit: 10Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
