apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: jellyfin
  labels:
    app: jellyfin
  annotations:
    svccontroller.k3s.cattle.io/lbpool: pool1
spec:
  ports:
    - name: http-web
      port: 8096
      targetPort: http-web-svc
      protocol: TCP
  selector:
    app: jellyfin
  type: ClusterIP
  # See for more information https://metallb.universe.tf/usage/#ip-address-sharing
  # externalTrafficPolicy: Cluster
