apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  ports:
    - name: http-web
      port: 8096
      targetPort: http-web-svc
      protocol: TCP
  selector:
    app: jellyfin
  type: LoadBalancer