apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
  annotations:
    svccontroller.k3s.cattle.io/lbpool: pool1
spec:
  ports:
    - name: www
      port: 8096
      targetPort: http-web
      protocol: TCP
  selector:
    app: jellyfin
  type: LoadBalancer
