apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-web-svc
      protocol: TCP
  selector:
    app: jellyfin
  type: ClusterIP