FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y libavcodec-dev libepoxy-dev libjpeg-dev libtiff5-dev libpng-dev \
                        libavdevice-dev libavformat-dev libswresample-dev git python3-pip git python3-jinja2 \
                        cmake libboost-program-options-dev libdrm-dev libexif-dev meson ninja-build \
                        libboost-dev libgnutls28-dev openssl libtiff5-dev pybind11-dev \
                        qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5 \
                        meson cmake python3-yaml python3-ply \
                        libglib2.0-dev libgstreamer-plugins-base1.0-dev

# Install fswebcam for usb camera use?
WORKDIR /build
RUN git clone https://github.com/raspberrypi/libcamera.git
WORKDIR libcamera

RUN meson setup build --buildtype=release -Dpipelines=rpi/vc4,rpi/pisp -Dipas=rpi/vc4,rpi/pisp -Dv4l2=true -Dgstreamer=enabled \
                        -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=enabled && \
                        ninja -C build && ninja -C build install

WORKDIR /build
RUN git clone https://github.com/raspberrypi/rpicam-apps.git
WORKDIR rpicam-apps

RUN meson setup build -Denable_libav=disabled -Denable_drm=enabled -Denable_egl=disabled -Denable_qt=disabled -Denable_opencv=disabled -Denable_tflite=disabled -Denable_hailo=disabled && \
    meson install -C build && \
    ldconfig

WORKDIR /root
RUN rm -rf /build

RUN apt-get purge -y libavcodec-dev libepoxy-dev libjpeg-dev libtiff5-dev libpng-dev \
                        libavdevice-dev libavformat-dev libswresample-dev git python3-pip git python3-jinja2 \
                        cmake libboost-program-options-dev libdrm-dev libexif-dev meson ninja-build \
                        libboost-dev libgnutls28-dev openssl libtiff5-dev pybind11-dev \
                        qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5 \
                        meson cmake python3-yaml python3-ply \
                        libglib2.0-dev libgstreamer-plugins-base1.0-dev

ENTRYPOINT rpicam-vid
