apiVersion: apps/v1
kind: Deployment
metadata:
  name: v4l2rtspserver
  namespace: v4l2rtspserver
  labels:
    app: v4l2rtspserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v4l2rtspserver
  template:
    metadata:
      name: v4l2rtspserver
      namespace: v4l2rtspserver
      labels:
        app: v4l2rtspserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: camera
                  operator: In
                  values:
                    - "0"
      containers:
      - name: v4l2rtspserver
        args:
          - "-p"
          - "8080"
        livenessProbe:
          tcpSocket:
            port: rtsp-tcp
          initialDelaySeconds: 120
        image: mpromonet/v4l2rtspserver:latest-arm64
        ports:
        - containerPort: 8554
          name: rtsp-udp
          protocol: UDP
        # - containerPort: 8554
        #   name: rtsp-tcp
        #   protocol: TCP
        - containerPort: 8080
          name: rtsp-http
        securityContext:
          privileged: true
        volumeMounts:
        - name: snd0
          mountPath: /dev/snd
        - name: password
          mountPath: /etc/user-password
        - name: video0
          mountPath: /dev/video0
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
      volumes:
      - name: video0
        hostPath: 
          path: /dev/video0
          type: CharDevice
      - name: snd0
        hostPath:
          path: /dev/snd
          type: Directory
      - name: password
        secret:
          secretName: user-password
          optional: false
          defaultMode: 0400
      dnsPolicy: ClusterFirst
      restartPolicy: Always
