apiVersion: v1
kind: Service
metadata:
  name: rtsp
  namespace: v4l2rtspserver
  labels:
    app: v4l2rtspserver
    camera: "0"
spec:
  ports:
  - name: 8554-8554-udp
    port: 8554
    protocol: UDP
    targetPort: rtsp-udp
  - name: 8554-8554-tcp
    port: 8554
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: v4l2rtspserver-http
  namespace: v4l2rtspserver
  labels:
    app: v4l2rtspserver
    camera: "0"
    svccontroller.k3s.cattle.io/lbpool: pool2
spec:
  ports:
  - name: 8080-8080-http
    port: 8080
    targetPort: rtsp-http
  type: LoadBalancer
