---
apiVersion: v1
kind: Service
metadata:
  name: rtsp0-udp
  namespace: v4l2rtspserver
  labels:
    app: rtsp0
    camera: "0"
spec:
  ports:
  - name: 8554-8554-udp
    port: 8554
    protocol: UDP
    targetPort: rtsp-udp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rtsp0-http
  namespace: v4l2rtspserver
  labels:
    app: rtsp0
    camera: "0"
    svccontroller.k3s.cattle.io/lbpool: pool1
spec:
  ports:
  - name: 8085-8085-http
    port: 8085
    targetPort: rtsp-http
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rtsp0-tcp
  namespace: v4l2rtspserver
  labels:
    app: rtsp0
    camera: "0"
spec:
  ports:
  - name: 8554-8554-tcp
    port: 8554
    protocol: TCP
  type: LoadBalancer
