---
apiVersion: v1
kind: Service
metadata:
  name: rtsp0-svc
  namespace: v4l2rtspserver
  labels:
    app: rtsp0
spec:
  selector:
    app: rtsp0
  ports:
  - name: rtsp-tcp-svc
    port: 555
    targetPort: rtsp-tcp
    protocol: TCP
  - name: rtsp-udp-svc
    port: 554
    targetPort: rtsp-udp
    protocol: UDP
  type: ClusterIP
