ARG IMAGE="localhost/arm64/archlinuxarm"
ARG IMAGE_TAG="generic"
FROM --platform=arm64 ${IMAGE}:${IMAGE_TAG} AS stage1

RUN --mount=type=cache,target=/var/cache/pacman/pkg --mount=type=cache,target=/etc/pacman.d/gnupg pacman-key --init \
                                                                                                  && pacman-key --populate archlinuxarm

FROM --platform=arm64 stage1 AS stage2

RUN --mount=type=cache,target=/var/cache/pacman/pkg --mount=type=cache,target=/etc/pacman.d/gnupg pacman --noconfirm -Rns openssh \
                                                                                                                          vi \
                                                                                                                          net-tools \
                                                                                                                          netctl \
                                                                                                                          nano \
                                                                                                                          linux-aarch64 \
                                                                                                                          linux-firmware

FROM --platform=arm64 stage2 AS stage3

RUN --mount=type=cache,target=/var/cache/pacman/pkg --mount=type=cache,target=/etc/pacman.d/gnupg pacman --noconfirm -Syu \
                                                                                                  && pacman --noconfirm -Scc
