---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - name: web
      protocol: TCP
      port: 8085
      targetPort: web-client
  type: ClusterIP
  sessionAffinity: ClientIP
  internalTrafficPolicy: Local
