---
apiVersion: v1
kind: ConfigMap
metadata:
  name: motion-conf
  namespace: motion
data:
  motion.conf: |
    # Documentation:  /usr/share/doc/motion/motion_guide.html

    ############################################################
    # System control configuration parameters
    ############################################################

    # Start in daemon (background) mode and release terminal.
    daemon off

    # Start in Setup-Mode, daemon disabled.
    setup_mode off

    # Level of log messages [1..9] (EMG, ALR, CRT, ERR, WRN, NTC, INF, DBG, ALL).
    log_level 7

    # Target directory for pictures, snapshots and movies
    target_dir /var/motion/

    ############################################################
    # Image Processing configuration parameters
    ############################################################

    # Image width in pixels.
    width 640

    # Image height in pixels.
    height 480

    # Maximum number of frames to be captured per second.
    # framerate 15

    # Text to be overlayed in the lower left corner of images
    text_left CAMERA1

    # Text to be overlayed in the lower right corner of images.
    text_right %Y-%m-%d\n%T-%q

    ############################################################
    # Motion detection configuration parameters
    ############################################################

    # Always save pictures and movies even if there was no motion.
    emulate_motion off

    # Threshold for number of changed pixels that triggers motion.
    threshold 1500

    # Noise threshold for the motion detection.
    noise_level 32

    # Despeckle the image using (E/e)rode or (D/d)ilate or (l)abel.
    despeckle_filter EedDl

    # Number of images that must contain motion to trigger an event.
    minimum_motion_frames 1

    # Gap in seconds of no motion detected that triggers the end of an event.
    event_gap 60

    # The number of pre-captured (buffered) pictures from before motion.
    pre_capture 3

    # Number of frames to capture after motion is no longer detected.
    post_capture 0

    ############################################################
    # Script execution configuration parameters
    ############################################################

    # Command to be executed when an event starts.
    ; on_event_start value

    # Command to be executed when an event ends.
    ; on_event_end value

    # Command to be executed when a movie file is closed.
    ; on_movie_end value

    ############################################################
    # Picture output configuration parameters
    ############################################################

    # Output pictures when motion is detected
    picture_output off

    # File name(without extension) for pictures relative to target directory
    picture_filename %Y%m%d%H%M%S-%q

    ############################################################
    # Movie output configuration parameters
    ############################################################

    # Create movies of motion events.
    movie_output on

    # Maximum length of movie in seconds.
    movie_max_time 300

    # The encoding quality of the movie. (0=use bitrate. 1=worst quality, 100=best)
    movie_quality 100

    # Container/Codec to used for the movie. See motion_guide.html
    movie_codec mkv

    # File name(without extension) for movies relative to target directory
    movie_filename %t-%v-%Y%m%d%H%M%S

    ############################################################
    # Webcontrol configuration parameters
    ############################################################

    # Port number used for the webcontrol.
    webcontrol_port 8080

    # Restrict webcontrol connections to the localhost.
    webcontrol_localhost on

    # Type of configuration options to allow via the webcontrol.
    webcontrol_parms 0

    ############################################################
    # Live stream configuration parameters
    ############################################################

    # The port number for the live stream.
    stream_port 8081

    # Restrict stream connections to the localhost.
    stream_localhost false

    ##############################################################
    # Directory to read '.conf' files for cameras.
    ##############################################################
    camera_dir /etc/motion/conf.d
