---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: target-dir-pvc
  namespace: motion
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-cctv
  resources:
    requests:
      storage: 3.9T
