---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  labels:
    app: pihole
  annotations:
    # TODO change this ingress class once it's created
    kubernetes.io/ingress.class: traefik
    # metallb.universe.tf/address-pool: server-pool
spec:
  selector:
    app: pihole
  ports:
  - name: 53-53-udp
    nodePort: 30053
    port: 1053
    protocol: UDP
    targetPort: dns-udp
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  labels:
    app: pihole
  annotations:
    # TODO change this ingress class once it's created
    kubernetes.io/ingress.class: traefik
    # metallb.universe.tf/address-pool: server-pool
spec:
  selector:
    app: pihole
  ports:
  - name: web-admin
    port: 8090
    targetPort: http-web-admin
    protocol: TCP
  type: LoadBalancer
