apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

secretGenerator:
- name: web-password
  namespace: jellyfin
  files:
  - web.password.txt

patches:
- path: deployment.yaml

patchesStrategicMerge:
- ingressroute.yaml
- middleware.yaml
