---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web-svc
  namespace: pihole
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  ports:
  - name: web-client
    port: 8091
    targetPort: web
    protocol: TCP
  type: ClusterIP
