---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-svc
  namespace: pihole
  annotations:
    metallb.io/address-pool: pool-external
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  ports:
  - name: 53-53-udp
    nodePort: 30053
    port: 1054
    protocol: UDP
    targetPort: pihole-dns
  type: ClusterIP
