apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-web-svc
  selector:
    app: jellyfin
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-conf
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  local:
    path: /pvs/jellyfin/conf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - compute
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4T
  local:
    path: /data/jellyfin
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - compute
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volumeType: local
  name: jellyfin-conf-pvc
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: jellyfin-conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volumeType: local
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4T
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: jellyfin-media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      name: jellyfin
      namespace: jellyfin
    spec:
      containers:
      - env:
        - name: JELLYFIN_PublishedServerUrl
          value: https://jellyfin.rick.expresso.lan
        image: docker.io/jellyfin/jellyfin:latest
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 5
          tcpSocket:
            port: http-web-svc
        name: jellyfin
        ports:
        - containerPort: 8096
          name: http-web-svc
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 10G
          requests:
            cpu: 1000m
            memory: 10G
        securityContext:
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
          privileged: true
        volumeMounts:
        - mountPath: /media
          name: media
        - mountPath: /config
          name: conf
        - mountPath: /dev/dri/renderD128
          name: dev-dri
        - mountPath: /dev/dri/card1
          name: card1
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
      - name: conf
        persistentVolumeClaim:
          claimName: jellyfin-conf-pvc
      - hostPath:
          path: /dev/dri/renderD128
          type: CharDevice
        name: dev-dri
      - hostPath:
          path: /dev/dri/card1
          type: CharDevice
        name: card1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.frontend.rule.type: PathPrefix
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  rules:
  - host: jellyfin.rick.expresso.lan
    http:
      paths:
      - backend:
          service:
            name: jellyfin
            port:
              number: 80
        path: /
        pathType: Prefix
