apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-log-pvc
  namespace: pihole
spec:
  volumeName: pihole-log
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-conf-pvc
  namespace: pihole
spec:
  volumeName: pihole-conf
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
