---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  jellyfin.override: |
    rewrite name regex (.*)-(rick)\.expresso\.lan {1}.cluster.{2}.local
    rewrite name suffix jellyfin.app.rick.expresso.lan. jellyfin.jellyfin.svc.cluster.local