apiVersion: k3d.io/v1alpha5
kind: Simple
registries: # define how registries should be created or used
  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.localhost`
    name: "${REGISTRY}"
    # Using container network to avoid unneeded port mapping
    # host: "0.0.0.0"
    # hostPort: "5000"
    proxy: # omit this to have a "normal" registry, set this to create a registry proxy (pull-through cache)
      remoteURL: "${MANAGEMENT_MIRROR_URL}" # Repository to mirror
      username: "${MANAGEMENT_REGISTRY_USER}" # unauthenticated
      password: "${MANAGEMENT_REGISTRY_PASS}" # unauthenticated
    volumes:
      - ${REGISTRY_IMAGE_STORE}:/var/lib/registry # persist registry data locally
