apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-nvme
  annotations:
    defaultVolumeType: "hostPath"
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/nvme
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-raid5
  annotations:
    defaultVolumeType: "hostPath"
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/data
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-raid10
  annotations:
    defaultVolumeType: "hostPath"
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/recordings
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Retain