---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool-kube-system-traefik-alloc
  namespace: metallb-system
spec:
  addresses:
    - 10.50.0.201/30
  avoidBuggyIPs: true
  serviceAllocation:
    priority: 50
    namespaces:
      - kube-system
    namespaceSelectors:
      - matchLabels:
          namespace: kube-system
    serviceSelectors:
      - matchExpressions:
          - {key: app.kubernetes.io/instance, operator: In, values: [traefik-kube-system]}
          - {key: svccontroller.k3s.cattle.io/lbpool, operator: In, values: [pool1]}
