---
# https://docs.k3s.io/cli/server
# Use embedded etcd
cluster-init: true
# Log level
# v: 4
debug: false
selinux: false
servicelb-namespace: kube-system-lb
tls-san:
  - 10.98.0.5
  - 10.50.0.2
  - 192.168.121.2
  - loadbalancer
  - rick.expresso.lan
  - rick-dev.expresso.lan
  - app.rick.expresso.lan
  - app.rick-dev.expresso.lan
secrets-encryption: true
default-local-storage-path: /mnt/nvme

# Network
# https://docs.k3s.io/installation/network-options#flannel-options
flannel-backend: vxlan
node-ip: 10.98.0.1
cluster-cidr: 10.42.0.0/16
service-cidr: 10.43.0.0/16

# kube apiserver
write-kubeconfig: /root/admin.kubeconfig
etcd-expose-metrics: true

# kubelet
kubelet-arg:
  - cgroup-root=/

# Kube Proxy
kube-proxy-arg:
  - pod-bridge-interface=pods
  - metrics-bind-address=0.0.0.0
