FROM debian:bookworm-slim

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && \
  apt-get --no-install-recommends install -y libavcodec59 libavdevice59 libavformat59 libavutil57 \
                                             libc6 libjpeg62-turbo libjpeg62-turbo libmariadb3 libmicrohttpd12 \
                                             libpq5 libsqlite3-0 libswscale6 libwebp7 libwebpmux3

ENV PKG_DIR=/usr/src/build
WORKDIR ${PKG_DIR}
ARG VERSION=4.7.0
ENV TAG=release-${VERSION}
ADD https://github.com/Motion-Project/motion/releases/download/${TAG}/bookworm_motion_${VERSION}-1_amd64.deb ./

RUN pwd && ls -alhtr
RUN apt-get install -y ./bookworm_motion_${VERSION}-1_amd64.deb

WORKDIR /root
RUN rm -rf ${PKG_DIR}

ENTRYPOINT [ "motion" ]
