apiVersion: apps/v1
kind: Deployment
metadata:
  name: gollum
  namespace: gollum
  labels:
    app: gollum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gollum
  template:
    metadata:
      name: gollum
      namespace: gollum
      labels:
        app: gollum
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - compute
      containers:
      - name: gollum
        image: gollumwiki/gollum:6.0.0
        args:
        - --allow-uploads
        - page
        - --page-file-dir
        - pages
        - --user-icons
        - gravatar
        - --emoji
        env:
        - name: APP_ENV
          value: production
        - name: GOLLUM_AUTHOR_USERNAME
          value: s-fairchild
        ports:
        - name: api
          containerPort: 4567
        - name: uploads
          containerPort: 22
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "2000m"
        volumeMounts:
        - name: uploads
          mountPath: /uploads
        - name: wiki
          mountPath: /wiki
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: wiki
        persistentVolumeClaim:
          claimName: wiki-pvc