apiVersion: v1
kind: Service
metadata:
  name: gollum
  namespace: gollum
  labels:
    app: gollum
spec:
  selector:
    app: gollum
  ports:
    - name: www
      port: 4568
      targetPort: api
    - name: ssh
      port: 2222
      targetPort: uploads
  type: LoadBalancer
