servers: 3
agents: 3
apiVersion: k3d.io/v1alpha5
token: ${TOKEN}
hostAliases:
- hostnames:
  - morty.expresso.lan
  ip: 10.50.0.1
- hostnames:
  - rpi4.expresso.lan
  ip: 10.50.0.10
kind: Simple
kubeAPI:
  host: morty.expresso.lan
  hostIP: 10.50.0.2
  hostPort: "6444"
metadata:
  name: morty
network: k3d
options:
  k3d:
    disableImageVolume: false
    disableLoadbalancer: false
    disableRollback: false
    loadbalancer: {}
    timeout: 300000000000
    wait: true
  k3s:
    nodeLabels:
    - label: app=compute
      nodeFilters:
      - agent:*
  kubeconfig:
    switchCurrentContext: false
    updateDefaultKubeconfig: false
  runtime:
    ulimits: # allowed keys are: rttime, core, locks, msgqueue, nice, rss, rtprio, cpu, fsize, memlock, nofile, nproc, stack, data, sigpending
      - name: locks
        soft: 30000
        hard: 30000
      - name: nofile # Required for Jellyfin filesystem monitoring
        soft: 30000
        hard: 30000
registries: {}
