servers: 1
agents: 1
apiVersion: k3d.io/v1alpha5
token: ${K3S_TOKEN}
hostAliases:
- hostnames:
  - morty.expresso.lan
  ip: 10.50.0.1
kind: Simple
kubeAPI:
  host: rick.expresso.lan
  hostIP: 10.50.0.2
  hostPort: "6443"
metadata:
  name: rick
network: k3d-rick
options:
  k3d:
    disableImageVolume: false
    disableLoadbalancer: false
    disableRollback: false
    timeout: 300000000000
    wait: true
    loadbalancer:
      configOverrides:
        - settings.workerConnections=10000
  k3s:
    extraArgs:
    - arg: --tls-san=10.50.0.2 
      nodeFilters:
        - server:*
    - arg: --tls-san=10.50.0.1
      nodeFilters:
        - server:*
    - arg: --tls-san=rick.lan
      nodeFilters:
        - server:*
    - arg: --tls-san=morty.expresso.lan
      nodeFilters:
        - server:*
    - arg: --tls-san=morty.lan 
      nodeFilters:
        - server:*
    - arg: --tls-san=pihole.rick.expresso.lan
      nodeFilters:
        - server:*
    - arg: --tls-san=jellyfin.rick.expresso.lan
      nodeFilters:
        - server:*
    - arg: --tls-san=k3s-rick-agent-1
      nodeFilters:
        - server:*
    - arg: --tls-san=jellyfin.rick.expresso.lan
      nodeFilters:
        - server:*
    - arg: --tls-san=system:node:morty.expresso.lan
      nodeFilters:
        - server:*
    - arg: --debug
      nodeFilters:
        - server:*
        - agent:*
    nodeLabels:
    - label: app=compute
      nodeFilters:
      - agent:*
  kubeconfig:
    switchCurrentContext: true
    updateDefaultKubeconfig: true
  runtime:
    ulimits: # allowed keys are: rttime, core, locks, msgqueue, nice, rss, rtprio, cpu, fsize, memlock, nofile, nproc, stack, data, sigpending
      - name: locks
        soft: 30000
        hard: 30000
      - name: nofile # Required for Jellyfin filesystem monitoring
        soft: 30000
        hard: 30000
ports:
- nodeFilters:
  - loadbalancer
  port: 80:8000
- nodeFilters:
  - loadbalancer
  port: 443:8443
- nodeFilters:
  - agent:*
  port: "10.50.0.2:53:30053/tcp"
- nodeFilters:
  - agent:*
  port: "10.50.0.2:53:30053/udp"
# - nodeFilters:
#   - agent:3
#   port: "10.50.0.1:8554:32554/udp"
registries:
  use:
    - k3d-registry:5000 # Precreated k3d registry is required when using podman, see k3d registry --help for more info
volumes:
- nodeFilters:
  - agent:*
  volume: /data/jellyfin:/data/jellyfin:Z
- nodeFilters:
  - agent:*
  volume: /data/motion:/data/motion:Z
- nodeFilters:
  - agent:*
  volume: /dev/dri:/dev/dri:z
- nodeFilters:
  - agent:*
  volume: compute:/pvs:Z
- nodeFilters:
  - server:*
  volume: /var/local/etc/k3d/manifests:/var/lib/rancher/k3s/server/manifests/compute:Z
