apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  set:
  valuesContent: |-
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
        # -- Allows to return 503 when there is no endpoints available
        allowEmptyServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        # -- Allows to return 503 when there is no endpoints available
        allowEmptyServices: true
    hostNetwork: true
    rbac:
      enabled: true
      namespaced: false
    priorityClassName: "system-cluster-critical"
    nodeSelector:
      svccontroller.k3s.cattle.io/enablelb: "true"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "2.10.5"
      pullPolicy: IfNotPresent
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "app"
        operator: "Equal"
        values:
          - compute
        effect: "NoSchedule"
    service:
      enabled: true
      ## -- Single service is using `MixedProtocolLBService` feature gate.
      ## -- When set to false, it will create two Service, one for TCP and one for UDP.
      single: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: ippool-kube-system-traefik-alloc
        svccontroller.k3s.cattle.io/lbpool: pool1
      labels:
        svccontroller.k3s.cattle.io/lbpool: pool1
      ipFamilyPolicy: "SingleStack"
      spec:
        loadBalancerSourceRanges:
          - 10.50.0.0/24
        loadBalancerIP: 10.50.0.201
    logs:
      general:
        # format: json
        # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: INFO
      access:
        enabled: true

    # ports:
    #   traefik:
    #     port: "9000"
    #     expose: false
    #     exposedPort: "9000"
    #     protocol: TCP
    #   web:
    #     asDefault: false
    #     port: 8000
    #     expose: true
    #     exposedPort: 80
    #     protocol: TCP
    #   websecure:
    #     asDefault: true
    #     port: 8443
    #     expose: true
    #     exposedPort: 443
    #     protocol: TCP
    #   internal:
    #     type: ClusterIP
    #     labels:
    #       app.kubernetes.io/network: internal
    #     annotations: {}
    #     spec: {}
    #     loadBalancerSourceRanges:
    #       - 10.98.0.0/16
    #       - 10.43.0.0/16
    #       - 10.42.0.0/16
    #     externalIPs: []
    #     ipFamilies: [ "IPv4" ]
    #     ingressClass:
    #       enabled: true
    #       isDefaultClass: true
