---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-21.2.1+up21.2.0.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system-traefik
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-21.2.1+up21.2.0.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: false
        # -- Allows to return 503 when there is no endpoints available
        allowEmptyServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: false
        # -- Allows to return 503 when there is no endpoints available
        allowEmptyServices: true
        publishedService:
          enabled: true
          # Published Kubernetes Service to copy status from. Format: namespace/servicename
          # By default this Traefik service
          # pathOverride: ""
    hostNetwork: false
    rbac:
      enabled: true
      namespaced: true
    priorityClassName: "system-cluster-critical"
    nodeSelector:
      svccontroller.k3s.cattle.io/enablelb: "true"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "2.9.10"
      pullPolicy: IfNotPresent
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "app"
        operator: "Equal"
        values:
          - compute
        effect: "NoSchedule"
    service:
      enabled: true
      ## -- Single service is using `MixedProtocolLBService` feature gate.
      ## -- When set to false, it will create two Service, one for TCP and one for UDP.
      single: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      ipFamilyPolicy: "SingleStack"
      spec:
        loadBalancerSourceRanges:
          - 10.50.0.0/24
    logs:
      general:
        # format: json
        # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: ERROR
      access:
        enabled: false


    # ports:
    #   traefik:
    #     port: "9000"
    #     expose: false
    #     exposedPort: "9000"
    #     protocol: TCP
    #   web:
    #     asDefault: false
    #     port: 8000
    #     expose: true
    #     exposedPort: 80
    #     protocol: TCP
    #   websecure:
    #     asDefault: true
    #     port: 8443
    #     expose: true
    #     exposedPort: 443
    #     protocol: TCP
    #   internal:
    #     type: ClusterIP
    #     labels:
    #       app.kubernetes.io/network: internal
    #     annotations: {}
    #     spec: {}
    #     loadBalancerSourceRanges: []
    #     externalIPs: []
    #     ipFamilies: [ "IPv4","IPv6" ]
    #     ingressClass:
    #       enabled: true
    #       isDefaultClass: true
