apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-cname-records
  namespace: pihole
data:
  05-pihole-custom-cname.conf: |

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-conf-port
  namespace: pihole
data:
  port.conf: |
    port=1053
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-local-records
  namespace: pihole
data:
  custom.list: |
    10.50.0.100 r10.expresso.lan
    10.50.0.50 rh-thinkpad-p1.expresso.lan
    10.50.0.10 rpi4.expresso.lan
    10.50.0.2 rick.expresso.lan
    10.50.0.1 expresso.lan
