apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  namespace: pihole
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      namespace: pihole
      name: pihole
      labels:
        app: pihole
        providers.docker.network: "k3d"
        entrypoints.web.address: "pihole.rick.expresso.lan"
        entrypoints.web.http.redirections.entrypoint.to: websecure
        entrypoints.websecure.address: "pihole.rick.expresso.lan"
        certificatesresolvers.letsencrypt.acme.httpchallenge: "true"
        certificatesresolvers.letsencrypt.acme.storage: acme.json
        certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint: web
        traefik.http.routers.pihole.entrypoints: "websecure"
        traefik.http.routers.pihole.tls: "true"
        traefik.http.routers.pihole.tls.certresolver: letsencrypt
        traefik.http.services.pihole.loadbalancer.server.port: "80"
    spec:
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: pihole-conf-pvc
        - name: pihole-custom
          configMap:
            name: pihole-custom
            optional: false
        - name: webpassword
          secret:
            secretName: webpassword
            optional: false
            defaultMode: 0400
        - name: unbound-config
          persistentVolumeClaim:
            claimName: unbound-conf-pvc
            readOnly: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - compute
      hostname: pihole
      automountServiceAccountToken: false
      dnsPolicy: None
      enableServiceLinks: false
      dnsConfig:
        nameservers:
          - "127.0.0.1"
          - "1.1.1.1"
      restartPolicy: Always
      containers:
      - name: pihole
        image: docker.io/pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        # See this for all env variables available https://github.com/pi-hole/docker-pi-hole#environment-variables
        env:
        # - name: PROXY_LOCATION
        #   value: "pihole.rick.expresso.lan"
        - name: VIRTUAL_HOST
          value: "pihole.rick.expresso.lan"
        - name: ServerIP
          value: "10.50.0.2"
        - name: TZ
          value: "America/New_York"
        - name: DNSMASQ_LISTENING
          value: "all"
        - name: FTLCONF_LOCAL_IPV4
          value: "10.50.0.2"
        - name: PIHOLE_DNS_
          value: "127.0.0.1#5335"
          # value: "8.8.8.8;8.8.4.4"
        - name: DHCP_ACTIVE
          value: "false"
        - name: TEMPERATUREUNIT
          value: "f"
        - name: WEBTHEME
          value: "default-darker"
        - name: WEB_PORT
          value: "8090"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: webpassword
              key: admin
              optional: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "150Mi"
            cpu: "5000m"
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: http-admin-web
          containerPort: 8090
          protocol: TCP
        securityContext:
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        volumeMounts:
        - name: conf
          mountPath: /etc/pihole
      - name: unbound
        image: madnuttah/unbound:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "100Mi"
            cpu: "30m"
          limits:
            memory: "100Mi"
            cpu: "30m"
        # ports:
        # - name: dns-unbound-udp
        #   containerPort: 5353
        #   protocol: UDP
        # - name: dns-unbound-tcp
        #   containerPort: 5353
        #   protocol: TCP
        volumeMounts:
          - name: unbound-config
            mountPath: /opt/unbound/etc/unbound
            readOnly: true
