apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  namespace: pihole
  name: pihole
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        namespace: pihole
      name: pihole
    spec:
      hostname: pihole
      automountServiceAccountToken: false
      dnsPolicy: None
      enableServiceLinks: false
      dnsConfig:
        nameservers:
          - "127.0.0.1"
          - "1.1.1.1"
      restartPolicy: Always
      volumes:
        - name: webpassword
          readOnly: true
          mountPath: /var/local/etc/webpassword
      # volumes:
      #   - name: pihole-log
      #     persistentVolumeClaim:
      #       claimName: pihole-log-pvc
        # - name: pihole-conf
        #   persistentVolumeClaim:
        #     claimName: pihole-conf-pvc
      containers:
      - name: pihole
        image: docker.io/pihole/pihole:latest
        # See this for all env variables available https://github.com/pi-hole/docker-pi-hole#environment-variables
        env:
        - name: PROXY_LOCATION
          value: "pihole.rick.expresso.lan"
        - name: VIRTUAL_HOST
          value: "pihole.rick.expresso.lan"
        - name: ServerIP
          value: "10.50.0.2"
        - name: TZ
          value: "America/New_York"
        - name: DNSMASQ_LISTENING
          value: "all"
        - name: FTLCONF_LOCAL_IPV4
          value: "10.50.0.2"
        - name: PIHOLE_DNS_
          value: "8.8.8.8;4.4.4.4a"
        - name: DHCP_ACTIVE
          value: "false"
        - name: TEMPERATUREUNIT
          value: f
        - name: WEBTHEME
          value: "default-darker"
        - name: WEB_PORT
          value: "80"
        # - name: WEBPASSWORD
        #   value: password
        - name: WEBPASSWORD_FILE
          value: "/var/local/etc/webpassword"
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "150Mi"
            cpu: "5000m"
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: http-admin-web
          containerPort: 80
          protocol: TCP
        securityContext:
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        # volumeMounts:
        # - name: pihole-log
        #   mountPath: /var/log/
        # - name: pihole-conf
        #   mountPath: /etc/pihole/