apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  namespace: pihole
  name: pihole
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 30%
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      namespace: pihole
      name: pihole
      labels:
        app: pihole
    spec:
      volumes:
        - name: setup
          configMap:
            name: setup-vars
            optional: false
        - name: conf
          persistentVolumeClaim:
            claimName: pihole-conf-pvc
        - name: pihole-local
          configMap:
            name: pihole-local-records
            optional: false
        - name: pihole-cname
          configMap:
            name: pihole-cname-records
            optional: false
        - name: webpassword
          secret:
            secretName: webpassword
            optional: false
            defaultMode: 0400
        - name: unbound-config
          persistentVolumeClaim:
            claimName: unbound-conf-pvc
            readOnly: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - compute
      hostname: pihole
      automountServiceAccountToken: false
      dnsPolicy: None
      enableServiceLinks: false
      dnsConfig:
        nameservers:
          - "127.0.0.1"
          - "1.1.1.1"
      restartPolicy: Always
      containers:
      - name: pihole
        image: docker.io/pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        # See this for all env variables available https://github.com/pi-hole/docker-pi-hole#environment-variables
        env:
        # - name: PROXY_LOCATION
        #   value: "pihole.rick.expresso.lan"
        - name: VIRTUAL_HOST
          value: "pihole.rick.expresso.lan"
        - name: ServerIP
          value: "10.50.0.2"
        - name: TZ
          value: "America/New_York"
        - name: DNSMASQ_LISTENING
          value: "all"
        - name: FTLCONF_LOCAL_IPV4
          value: "10.50.0.2"
        - name: PIHOLE_DNS_
          value: "127.0.0.1#5335"
        - name: DHCP_ACTIVE
          value: "false"
        - name: TEMPERATUREUNIT
          value: "f"
        - name: WEBTHEME
          value: "default-darker"
        - name: WEB_PORT
          value: "8090"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: webpassword
              key: admin
              optional: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "150Mi"
            cpu: "5000m"
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: http-admin-web
          containerPort: 8090
          protocol: TCP
        securityContext:
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        volumeMounts:
        - name: setup
          mountPath: /etc/pihole/setupVars.conf
          mountPropagation: None
          subPath: setupVars.conf
        - name: pihole-cname
          mountPath: /etc/dnsmasq.d/05-pihole-custom-cname.conf
          mountPropagation: None
          subPath: 05-pihole-custom-cname.conf
        - name: pihole-local
          mountPath: /etc/pihole/custom.list
          mountPropagation: None
          subPath: custom.list
        livenessProbe:
          exec:
            command:
            - dig
            - www.google.com
            - "@localhost"
          initialDelaySeconds: 60
          periodSeconds: 5
      - name: unbound
        image: madnuttah/unbound:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "100Mi"
            cpu: "30m"
          limits:
            memory: "100Mi"
            cpu: "30m"
        volumeMounts:
          - name: unbound-config
            mountPath: /opt/unbound/etc/unbound
            readOnly: true
        livenessProbe:
          exec:
            command:
            - nslookup
            - www.google.com
            - localhost
          initialDelaySeconds: 60
          periodSeconds: 5
