apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.frontend.rule.type: PathPrefix
  labels:
    app: pihole
  name: pihole-admin
  namespace: pihole
spec:
  rules:
  - host: pihole.rick.expresso.lan
    http:
      paths:
      - backend:
          service:
            name: pihole-web
            port:
              name: pihole-web
        path: /admin
        pathType: Prefix
