apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-conf-pvc
  namespace: pihole
  annotations:
    volumeType: local
spec:
  volumeName: pihole-conf
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
