kind: Service
apiVersion: v1
metadata:
  name: pihole-web
  namespace: pihole
  labels:
    app: pihole
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http-admin-web
    protocol: TCP
  selector:
    app: pihole
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  ports:
  - name: 53-53-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: 53-53-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  selector:
    app: pihole
