---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  ports:
  - name: 53-53-udp
    nodePort: 30053
    port: 1053
    protocol: UDP
    targetPort: dns-udp
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  selector:
    app: pihole
    # svccontroller.k3s.cattle.io/lbpool: pool1
  ports:
  - name: web-admin
    port: 8090
    targetPort: http-web-admin
    protocol: TCP
  type: LoadBalancer
