---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  labels:
    app: pihole
spec:
  ports:
  - name: 53-53-udp
    nodePort: 30053
    port: 53
    protocol: UDP
    targetPort: dns-tcp
  - name: 53-53-tcp
    nodePort: 30053
    port: 53
    protocol: TCP
    targetPort: dns-udp
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  selector:
    app: pihole
  ports:
    - protocol: UDP
      port: 30053
      targetPort: 30053
  type: LoadBalancer
