---
- name: My first play
  hosts: rpi02ws
  remote_user: alarm
  become: true
  tasks:
  - name: Create secret
    containers.podman.podman_secret:
      state: present
      name: k3s-token
      data: "{{ K3S_TOKEN }}"
