---
- name: Standup K3S Agent Nodes
  hosts: raspberry_pis
  remote_user: root
  vars:
    quadlet_base_dir: /etc/containers/systemd
    sysconfig_dir: /usr/local/etc/sysconfig
    kubelet_agent_dir: /usr/local/var/lib/k3s/agent/kubelet
  tasks:
    - name: Delete directory "{{ sysconfig_dir }}"
      ansible.builtin.file:
        path: "{{ sysconfig_dir }}"
        state: absent
        mode: '0755'
      tags:
        - quadlet
        - environment
        - directories

    - name: Create directory "{{ sysconfig_dir }}"
      ansible.builtin.file:
        path: "{{ sysconfig_dir }}"
        state: directory
        mode: '0755'
      tags:
        - quadlet
        - environment
        - directories

    - name: Copy EnvironmentFile for to k3s container use {{ COMMON.FILES.PROD.SYSCONFIG.K3S_ENV }}
      ansible.builtin.copy:
        src: "{{ COMMON.FILES.PROD.SYSCONFIG.K3S_ENV }}"
        dest: "{{ sysconfig_dir }}/k3s"
        owner: root
        group: root
        mode: '0644'
      tags:
        - k3s
        - environment

    - name: Copy podman quadlet env file "{{ COMMON.FILES.PROD.SYSCONFIG.PODMAN_ENV }}"
      ansible.builtin.copy:
        src: "{{ COMMON.FILES.PROD.SYSCONFIG.PODMAN_ENV }}"
        dest: "{{ sysconfig_dir }}/podman-options"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - environment
    
    - name: Create /etc/containers/systemd Directory - "{{ quadlet_base_dir }}"
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}"
        state: directory
        mode: '0755'
      tags:
        - quadlet

    - name: Copy k3s.image podman quadlet file
      ansible.builtin.copy:
        src: "{{ COMMON.DIRS.BASE.PODMAN.IMAGES }}/k3s/k3s.image"
        dest: "{{ quadlet_base_dir }}/k3s.image"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - images

    - name: Copy end0.network.d/routes.conf
      ansible.builtin.copy:
        content: |
          [Route]
          Destination={{ NETWORK.K3S.SUBNETS.SERVER }}
          Source={{ K3S.NETWORK.KUBE_AGENT.SUBNET }}
          Scope=link
          Table=main
          NextHop=1

          [Route]
          Destination={{ NETWORK.K3S.SUBNETS.AGENT }}
          Source={{ K3S.NETWORK.KUBE_AGENT.SUBNET }}
          Scope=link
          Table=main
          NextHop=1

          [NextHop]
          Id=1
          Gateway={{ NETWORK.K3S.APISERVER_LB.EXTERNAL }}

        dest: /etc/systemd/network/end0.network.d/routes.conf
        owner: root
        group: root
        mode: '0644'
      tags:
        - systemd-networkd.routes

    - name: Reload systemd-networkd configs
      ansible.builtin.command:
        argv:
          - networkctl
          - reload
      register: reload_output
      changed_when: reload_output.rc == 0
      tags:
        - systemd-networkd.routes

    - name: Delete {{ kubelet_agent_dir }} directory
      ansible.builtin.file:
        path: "{{ kubelet_agent_dir }}"
        state: absent
      tags:
        - kubelet

    - name: Create {{ kubelet_agent_dir }} directory
      ansible.builtin.file:
        path: "{{ kubelet_agent_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      tags:
        - kubelet

    # - name: Copy {{ kubelet_agent_dir }}/seccomp/profiles directory
      # ansible.builtin.copy:
        # src: "{{ COMMON.DIRS.BASE.KUBELET.AGENT }}/seccomp/profiles/"
        # dest: "{{ kubelet_agent_dir }}/seccomp/profiles/"
        # owner: root
        # group: root
        # directory_mode: '0755'
      # tags:
        # - kubelet.seccomp

    - name: Delete directory kube-agent.network.d - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/kube-agent.network.d"
        state: absent
      tags:
        - quadlet
        - networks

    - name: Create directory kube-agent.network.d - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/kube-agent.network.d"
        state: directory
        mode: '0755'
      tags:
        - quadlet
        - networks

    - name: Copy kube-agent.network podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        src: "{{ COMMON.DIRS.BASE.PODMAN.NETWORKS.KUBE_AGENT }}/kube-agent.network"
        dest: "{{ quadlet_base_dir }}/kube-agent.network"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - networks

    - name: Copy kube-agent.network.d/subnet.conf podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        content: |
          [Network]
          Subnet={{ K3S.NETWORK.KUBE_AGENT.SUBNET }}
        dest: "{{ quadlet_base_dir }}/kube-agent.network.d/subnet.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - networks

    - name: Copy kube-agent.network.d/dns.conf podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        content: |
          [Network]
          # kube-agent (podman) dns server on rick.expresso.lan
          DNS= {{ NETWORK.PODMAN.AGENT.DNS_IP }}
        dest: "{{ quadlet_base_dir }}/kube-agent.network.d/dns.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - networks

    - name: Copy k3s-agent@.container podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        src: "{{ COMMON.DIRS.BASE.PODMAN.CONTAINERS }}/k3s-agent@.container"
        dest: "{{ quadlet_base_dir }}/k3s-agent@.container"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - containers

    - name: Delete directory k3s-agent@<K3S.INSTANCE>.d/ - K3S.INSTANCE - {{ K3S.INSTANCE }}
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S.INSTANCE }}.container.d"
        state: absent
        mode: '0755'
      tags:
        - quadlet
        - containers

    - name: Create directory k3s-agent@<K3S.INSTANCE>.d/ - K3S.INSTANCE - {{ K3S.INSTANCE }}
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S.INSTANCE }}.container.d"
        state: directory
        mode: '0755'
      tags:
        - quadlet
        - containers

    - name: Copy k3s-agent@<K3S.INSTANCE>.container.d/exec-extra-args.conf - K3S.INSTANCE - {{ K3S.INSTANCE }}
      ansible.builtin.copy:
        content: |
          [Service]
          # https://docs.k3s.io/cli/agent#node-labels-and-taints-for-agents
          Environment=AGENT_EXTRA_ARGS=--node-label={{ K3S.NODE_LABELS.RTSP }}
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S.INSTANCE }}.container.d/exec-extra-args.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - containers

    - name: Copy k3s-agent@<K3S.INSTANCE>.container.d/node-ip.conf - K3S.INSTANCE - {{ K3S.INSTANCE }}
      ansible.builtin.copy:
        content: |
          [Service]
          Environment=NODE_IP={{ K3S.NETWORK.NODE_IP }}
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S.INSTANCE }}.container.d/node-ip.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - containers

    - name: Copy k3s-agent@<K3S.INSTANCE>.container.d/devices.conf - K3S.INSTANCE - {{ K3S.INSTANCE }}
      ansible.builtin.copy:
        content: |
          [Container]
          AddDevice=-{{ PODMAN.DEVICES.CAMERAS.USB.INDEX_0 }}:/dev/video0:rwm
          AddDevice=-{{ PODMAN.DEVICES.CAMERAS.USB.INDEX_1 }}:/dev/video1:rwm
          # https://www.raspberrypi.com/documentation/computers/camera_software.html#device-nodes-when-using-libcamera
          AddDevice=-{{ RPI4.VC4.ENCODE }}:{{ RPI4.VC4.ENCODE }}:rwm
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S.INSTANCE }}.container.d/devices.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - containers

    - name: Copy k3s-agent@<K3S.INSTANCE>.container.d/limits.conf - K3S.INSTANCE - {{ K3S.INSTANCE }}
      ansible.builtin.copy:
        content: |
          [Container]
          # memory cgroup controller must be enabled by adding cgroup_enable=memory to /boot/cmdline.txt
          # https://archlinuxarm.org/forum/viewtopic.php?f=23&t=17131#p73138
          # https://github.com/raspberrypi/linux/pull/6524
          Memory={{ PODMAN.LIMITS.MEMORY }}
          PodmanArgs=--cpus={{ PODMAN.LIMITS.CPU }}
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S.INSTANCE }}.container.d/limits.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - containers

    - name: Delete directory k3s-agent@.container.d - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/k3s-agent@.container.d"
        state: absent
        mode: '0755'
      tags:
        - quadlet
        - networks

    - name: Create directory k3s-agent@.container.d - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/k3s-agent@.container.d"
        state: directory
        mode: '0755'
      tags:
        - quadlet
        - networks

    - name: Copy k3s-agent@.container.d/kube-agent-network.conf - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        src: "{{ COMMON.FILES.BASE.QUADLET.K3S_AGENT.NETWORK }}"
        dest: "{{ quadlet_base_dir }}/k3s-agent@.container.d/{{ NETWORK.PODMAN.AGENT.SYSTEMD_SERVICE }}.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - quadlet
        - containers

    - name: Copy k3s-agent@.container.d/global-debug.conf podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        content: |
          [Container]
          GlobalArgs=--log-level=debug
        dest: "{{ quadlet_base_dir }}/k3s-agent@.container.d/log-level.conf"
        owner: root
        group: root
        mode: '0644'
      tags:
        - never
        - debug
        - quadlet.generator

    - name: Create symlink k3s-agent@<K3S.INSTANCE>.container - K3S.INSTANCE - {{ K3S.INSTANCE }}
      ansible.builtin.file:
        src: "{{ quadlet_base_dir }}/k3s-agent@.container"
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S.INSTANCE }}.container"
        owner: root
        group: root
        state: link
      tags:
        - quadlet
        - containers

    - name: Run podman-systemd-generator
      ansible.builtin.command:
        argv:
          - /usr/lib/podman/quadlet
          - /run/systemd/generator/
      register: generator_output
      changed_when: generator_output.rc == 0
      tags:
        - images
        - containers
        - networks
        - quadlet.files
        - quadlet.generator

    - name: (Re)Start k3s-image.service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: k3s-image
      tags:
        - quadlet.files
        - quadlet.generator
        - images

    # Gracefully stop k3s-agent before deleting the network
    - name: Stop and mask k3s-agent service
      ansible.builtin.systemd_service:
        name: k3s-agent@{{ K3S.INSTANCE }}
        state: stopped
        masked: true
      tags:
        - networks
        - containers
        - quadlet.files
        - quadlet.generator

    - name: Delete a podman network {{ NETWORK.PODMAN.AGENT.NAME }}
      containers.podman.podman_network:
        name: "{{ NETWORK.PODMAN.AGENT.NAME }}"
        state: absent
        force: true

    - name: (Re)Start service {{ NETWORK.PODMAN.AGENT.SYSTEMD_SERVICE }}
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: "{{ NETWORK.PODMAN.AGENT.SYSTEMD_SERVICE }}"
      tags:
        - quadlet
        - networks

    - name: Create or Update k3s-token podman secret
      containers.podman.podman_secret:
        state: present
        name: k3s-token
        # recreate the secret
        force: true
        data: "{{ K3S_TOKEN }}"
      when: K3S_TOKEN is defined
      tags:
        - k3s
        - k3s-token
        - secrets

    - name: (Re)Start "k3s-agent@<K3S.INSTANCE>.service"- K3S.INSTANCE - "{{ K3S.INSTANCE }}"
      ansible.builtin.systemd_service:
        name: "k3s-agent@{{ K3S.INSTANCE }}.service"
        state: restarted
        daemon_reload: true
        masked: false
      tags:
        - networks
        - containers
        - quadlet
        - quadlet.files
        - quadlet.generator
