---
- name: Standup k3s agent node on Raspberry Pi Zero 2W (rpi02w)
  hosts: rpi02ws
  remote_user: alarm
  become: true
  vars:
    quadlet_base_dir: /etc/containers/systemd
    sysconfig_dir: /usr/local/etc/sysconfig
  tasks:
    - name: Enable podman.socket
      ansible.builtin.systemd_service:
        name: podman.socket
        enabled: true
      tags:
        - services

    - name: Create directory "{{ sysconfig_dir }}"
      ansible.builtin.file:
        path: "{{ sysconfig_dir }}"
        state: directory
        mode: '0750'
      tags:
        - quadlet
        - environment
        - directories

    - name: Create directory k3s-agent@.container.d
      ansible.builtin.file:
        path: "{{ sysconfig_dir }}"
        state: directory
        mode: '0750'
      tags:
        - quadlet
        - environment
        - directories

    # - name: Copy "{{ K3S_ENV_SRC }}"
    #   ansible.builtin.copy:
    #     src: "{{ K3S_ENV_SRC }}"
    #     dest: "{{ sysconfig_dir }}/k3s"
    #     owner: root
    #     group: root
    #     mode: '0600'

    - name: Copy podman quadlet env file "{{ PODMAN_OPTIONS_SRC }}"
      ansible.builtin.copy:
        src: "{{ PODMAN_OPTIONS_SRC }}"
        dest: "{{ sysconfig_dir }}/podman-options"
        owner: root
        group: root
        mode: '0600'
      tags:
        - quadlet
        - environment

    - name: Copy k3s.image podman quadlet file
      ansible.builtin.copy:
        src: ../../butane/base/podman/images/k3s.image
        dest: "{{ quadlet_base_dir }}/k3s.image"
        owner: root
        group: root
        mode: '0600'
      tags:
        - quadlet
        - images

    - name: Create directory <quadlet_base_dir>/kube-agent.network.d - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/kube-agent.network.d"
        state: directory
        mode: '0750'
      tags:
        - quadlet
        - networks

    - name: Copy <quadlet_base_dir>/kube-agent.network podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        src: ../../butane/base/podman/networks/kube-agent.network
        dest: "{{ quadlet_base_dir }}/kube-agent.network"
        owner: root
        group: root
        mode: '0600'
      tags:
        - quadlet
        - networks

    - name: Copy kube-agent.network.d/subnet.conf podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        content: |
          [Network]
          Subnet={{ KUBE_AGENT_SUBNET }}
          Gateway={{ KUBE_AGENT_GATEWAY }}
          PodmanArgs=--route=10.43.0.0/16,10.50.0.2
        dest: "{{ quadlet_base_dir }}/kube-agent.network.d/subnet.conf"
        owner: root
        group: root
        mode: '0600'
      tags:
        - quadlet
        - networks

    - name: Copy <quadlet_base_dir>/k3s-agent@.container podman quadlet file - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        src: ../../butane/base/podman/containers/agent/k3s-agent@.container
        dest: "{{ quadlet_base_dir }}/k3s-agent@.container"
        owner: root
        group: root
        mode: '0640'
      tags:
        - quadlet
        - containers

    - name: Copy k3s-agent@<K3S_AGENT_INSTANCE>.container.d/exec-extra-args.conf - K3S_AGENT_INSTANCE - {{ K3S_AGENT_INSTANCE }}
      ansible.builtin.copy:
        content: |
          [Service]
          # https://docs.k3s.io/cli/agent#node-labels-and-taints-for-agents
          Environment=AGENT_EXTRA_ARGS=--node-label=rtsp=0
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S_AGENT_INSTANCE }}.container.d/exec-extra-args.conf"
        owner: root
        group: root
        mode: '0640'
      tags:
        - quadlet
        - containers

    - name: Create directory <quadlet_base_dir>/k3s-agent@<K3S_AGENT_INSTANCE>.d/ - K3S_AGENT_INSTANCE - {{ K3S_AGENT_INSTANCE }}
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S_AGENT_INSTANCE }}.container.d"
        state: directory
        mode: '0750'
      tags:
        - quadlet
        - networks

    - name: Copy k3s-agent@<K3S_AGENT_INSTANCE>.container.d/node-ip.conf - K3S_AGENT_INSTANCE - {{ K3S_AGENT_INSTANCE }}
      ansible.builtin.copy:
        content: |
          [Service]
          Environment=NODE_IP={{ NODE_IP }}
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S_AGENT_INSTANCE }}.container.d/node-ip.conf"
        owner: root
        group: root
        mode: '0640'
      tags:
        - quadlet
        - containers

    - name: Create directory <quadlet_base_dir>/k3s-agent@.container.d - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.file:
        path: "{{ quadlet_base_dir }}/k3s-agent@.container.d"
        state: directory
        mode: '0750'
      tags:
        - quadlet
        - networks

    - name: Copy <quadlet_base_dir>/k3s-agent@.container.d/add-hosts.conf - quadlet_base_dir "{{ quadlet_base_dir }}/"
      ansible.builtin.copy:
        content: |
          [Container]
          AddHost=k3s-apiserverlb-0:{{ APISERVER_INTERNAL_LB }}
        dest: "{{ quadlet_base_dir }}/k3s-agent@.container.d/add-hosts.conf"
        owner: root
        group: root
        mode: '0640'
      tags:
        - quadlet
        - containers

    - name: Create symlink k3s-agent@<K3S_AGENT_INSTANCE>.container - K3S_AGENT_INSTANCE - {{ K3S_AGENT_INSTANCE }}
      ansible.builtin.file:
        src: "{{ quadlet_base_dir }}/k3s-agent@.container"
        dest: "{{ quadlet_base_dir }}/k3s-agent@{{ K3S_AGENT_INSTANCE }}.container"
        owner: root
        group: root
        state: link
      tags:
        - quadlet
        - containers

    # TODO add check to see if quadlet files have newer timestamp than now
    # https://ansible.readthedocs.io/projects/lint/rules/no-changed-when/
    - name: Run quadlet to create systemd services
      ansible.builtin.command:
      # register: my_output # <- Registers the command output.
      # changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
        argv:
          - /usr/lib/podman/quadlet
          - /run/systemd/generator/
      tags:
        - quadlet
        - podman-systemd-generator
        - images
        - containers

    - name: (Re)Start k3s-image.service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: k3s-image
      tags:
        - quadlet
        - images

    - name: (Re)Start kube-agent-network.service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: kube-agent-network
      tags:
        - quadlet
        - networks

    - name: (Re)Start "k3s-agent@<K3S_AGENT_INSTANCE>.service"- K3S_AGENT_INSTANCE - "{{ K3S_AGENT_INSTANCE }}"
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: "k3s-agent@{{ K3S_AGENT_INSTANCE }}.service"
      tags:
        - quadlet
        - containers

    - name: Create or Update k3s-token podman secret
      containers.podman.podman_secret:
        state: present
        name: k3s-token
        data: "{{ K3S_TOKEN }}"
      when: K3S_TOKEN is defined
      tags:
        - k3s
        - k3s-token
        - secrets
