---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  labels:
    app: pihole
    svccontroller.k3s.cattle.io/lbpool: pool0
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-www
  namespace: pihole
  labels:
    app: pihole
    svccontroller.k3s.cattle.io/lbpool: pool0
