---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-default
  annotations:
    defaultVolumeType: "hostPath"
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/local-path/default
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-appdata
  annotations:
    defaultVolumeType: "hostPath"
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/local-path/appdata
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-cctv
  annotations:
    defaultVolumeType: "hostPath"
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/local-path/cctv
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Retain
