---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-pvc
  namespace: jellyfin
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
