apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-conf
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  local:
    path: /mnt/nvme/pihole/etc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - "compute"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unbound-conf
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: local-path
  local:
    path: /mnt/nvme/unbound/etc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - "compute"
  persistentVolumeReclaimPolicy: Retain