---
# https://docs.k3s.io/cli/server
servicelb-namespace: kube-system-lb
tls-san:
  - 10.42.0.5
  - 10.50.0.2
  - apiserverlb
  - rick.expresso.lan
  - app.rick.expresso.lan
secrets-encryption: true
default-local-storage-path: /mnt/nvme

# Network
# https://docs.k3s.io/installation/network-options#flannel-options
flannel-backend: wireguard-native

# kubelet
kubelet-arg:
  - cgroup-root=/

# Kube Proxy
kube-proxy-arg:
  - pod-bridge-interface=pod0
  - metrics-bind-address=0.0.0.0
