---
# https://docs.k3s.io/cli/server
debug: false
selinux: true
server: https://10.98.0.5:6443
servicelb-namespace: kube-system-lb
tls-san:
  - 10.98.0.5
  - loadbalancer
  - 10.50.0.2
  - rick.expresso.lan
  - app.rick.expresso.lan
secrets-encryption: true
default-local-storage-path: /mnt/nvme

# Network
# https://docs.k3s.io/installation/network-options#flannel-options
flannel-backend: vxlan
node-ip: 10.98.0.3
cluster-cidr: 10.42.0.0/16
service-cidr: 10.43.0.0/16
node-external-ip: 10.50.0.2

# kubelet
kubelet-arg:
  - cgroup-root=/

# Kube Proxy
kube-proxy-arg:
  - pod-bridge-interface=pods
  - metrics-bind-address=0.0.0.0
