---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mw-headers
  namespace: jellyfin
spec:
  headers:
    customFrameOptionsValue: 'allow-from https://app.jellyfin.expresso.lan'
    SSLHost: jellyfin.app.rick.expresso.lan
