apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-pvc
  namespace: pihole
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  storageClassName: local-path-nvme
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-pvc
  namespace: pihole
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  storageClassName: local-path-nvme
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
