---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mw-headers
  namespace: jellyfin
spec:
  headers:
    entryPoints:
      - websecure
    customResponseHeaders:
      X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      X-XSS-PROTECTION: "1"
      X-Forwarded-Proto: "https"
    stsSeconds: 315360000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    frameDeny: true
    contentTypeNosniff: true
    SSLForceHost: true
    STSIncludeSubdomains: true
    STSPreload: true
    browserXssFilter: true
